services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7765489129:AAECLQL8HdmJUWaws8IfqvWcLve7WWGOCgk
